/**
 * Send outreach emails in 3 groups:
 *   A: Clean tenants - "I built you a free AI assistant"
 *   B: Tenants with gaps - "I tested your site from a customer's perspective"
 *   C: Timeout tenants - same as A
 *
 * Reads group lists from /tmp/group-*.txt (generated by audit analysis).
 * Respects unsubscribe list. Includes List-Unsubscribe headers.
 *
 * Usage:
 *   RESEND_API_KEY=re_xxx npx tsx scripts/send-all-campaigns.ts --dry-run
 *   RESEND_API_KEY=re_xxx npx tsx scripts/send-all-campaigns.ts --send
 *   RESEND_API_KEY=re_xxx npx tsx scripts/send-all-campaigns.ts --send --group=a
 */

import { readFileSync } from "fs";

const BASE_URL = process.env.BASE_URL || "https://whisp.so";
const ADMIN_SECRET = process.env.ADMIN_SECRET || "whisp-admin-2026";
const RESEND_KEY = process.env.RESEND_API_KEY || "";
const FROM = "Jakub <jakub@whisp.so>";
const SEND = process.argv.includes("--send");
const GROUP = (process.argv.find(a => a.startsWith("--group="))?.split("=")[1] || "all");

function readIds(path: string): string[] {
  try { return readFileSync(path, "utf-8").trim().split("\n").filter(Boolean); }
  catch { return []; }
}

const GROUP_A = readIds("/tmp/group-a-clean.txt");
const GROUP_B = readIds("/tmp/group-b-filtered.txt");
const GROUP_C = readIds("/tmp/group-c-timeouts.txt");

const UNSUB = (email: string) => `<p style="font-size:11px;color:#999;"><a href="${BASE_URL}/unsubscribe?email=${encodeURIComponent(email)}" style="color:#999;">Unsubscribe</a></p>`;
const SIG = `<p>Jakub<br>whisp.so</p>`;

function emailClean(domain: string, demoUrl: string, email: string): { subject: string; html: string } {
  return {
    subject: `I built a free AI assistant for ${domain}`,
    html: `<p>Hi,</p>
<p>I built an AI assistant that reads ${domain} and answers visitor questions - pricing, services, location, hours, anything on your site.</p>
<p>It already knows your website. You can try it here:<br><a href="${demoUrl}">${demoUrl}</a></p>
<p>If you like it, I can set it up for you in 5 minutes - just reply to this email or <a href="https://cal.com/whisp/15min">book a quick call</a>.</p>
${SIG}
${UNSUB(email)}`,
  };
}

function emailGaps(domain: string, demoUrl: string, email: string): { subject: string; html: string } {
  return {
    subject: `I tested ${domain} from a customer's perspective`,
    html: `<p>Hi,</p>
<p>I built an AI that reads your website and answers visitor questions. I tested it on ${domain} - most questions got good answers, but a few common ones left visitors without a clear next step.</p>
<p>You can see exactly what it knows and what's missing:<br><a href="${demoUrl}">${demoUrl}</a></p>
<p>Want to fix the gaps? Reply here or <a href="https://cal.com/whisp/15min">book a quick call</a> - I'll set it up for free.</p>
${SIG}
${UNSUB(email)}`,
  };
}

function emailPersonal(domain: string, demoUrl: string, email: string): { subject: string; html: string } {
  return {
    subject: `Can I help ${domain} with AI?`,
    html: `<p>Hi,</p>
<p>I'm Jakub, I study Computer Science in Poland and I'm helping businesses onboard AI to grow. I built an AI assistant that reads your website and can answer customer questions 24/7.</p>
<p>I already made one for ${domain} - it knows your services, pricing, and everything on your site:<br><a href="${demoUrl}">${demoUrl}</a></p>
<p>If it's useful, I'll set it up for you for free - just reply or <a href="https://cal.com/whisp/15min">book a 15-min call</a>.</p>
${SIG}
${UNSUB(email)}`,
  };
}

async function main() {
  // Fetch tenants
  const resp = await fetch(`${BASE_URL}/api/admin/tenants?secret=${ADMIN_SECRET}`);
  const allTenants = (await resp.json()) as any[];
  const tenantMap = new Map(allTenants.map((t: any) => [t.id, t]));

  // Fetch unsubscribe list
  let unsubs: string[] = [];
  try {
    const unsubResp = await fetch(`${BASE_URL}/api/admin/unsubscribed?secret=${ADMIN_SECRET}`);
    if (unsubResp.ok) unsubs = (await unsubResp.json()) as string[];
  } catch {}
  const unsubSet = new Set(unsubs.map(e => e.toLowerCase()));

  // Already emailed (contact-info group)
  const alreadyEmailed = new Set(readIds("/tmp/already-emailed.txt"));

  let sent = 0, skipped = 0;
  const sentIds = new Set<string>();

  async function sendToGroup(ids: string[], template: "clean" | "gaps", label: string) {
    console.log(`\n=== ${label} (${ids.length} tenants) ===`);

    for (const id of ids) {
      const tenant = tenantMap.get(id);
      if (!tenant || !tenant.email) { skipped++; continue; }
      if (unsubSet.has(tenant.email.toLowerCase())) { console.log(`  UNSUB ${tenant.domain}`); skipped++; continue; }
      if (alreadyEmailed.has(id)) { console.log(`  ALREADY ${tenant.domain}`); skipped++; continue; }
      if (!tenant.email.includes("@") || tenant.email.includes("x0poTQTo7")) { skipped++; continue; }
      if (tenant.domain === "whisp.so" || tenant.domain === "flowstock.so") { skipped++; continue; }
      if (sentIds.has(id)) { console.log(`  DUP ${tenant.domain}`); skipped++; continue; }
      sentIds.add(id);

      const demoUrl = `${BASE_URL}/demo/${id}`;
      const { subject, html } = template === "clean"
        ? emailClean(tenant.domain, demoUrl, tenant.email)
        : template === "gaps"
        ? emailGaps(tenant.domain, demoUrl, tenant.email)
        : emailPersonal(tenant.domain, demoUrl, tenant.email);

      if (!SEND) {
        console.log(`  [DRY] ${tenant.domain} → ${tenant.email} (${template})`);
        sent++;
        continue;
      }

      const unsubUrl = `${BASE_URL}/unsubscribe?email=${encodeURIComponent(tenant.email)}`;
      try {
        const emailResp = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${RESEND_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: FROM, to: [tenant.email], subject, html,
            reply_to: "jakub@whisp.so",
            headers: {
              "List-Unsubscribe": `<${unsubUrl}>`,
              "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
            },
          }),
        });
        if (emailResp.ok) {
          sent++;
          console.log(`  ✉️  ${tenant.domain} → ${tenant.email}`);
        } else {
          const err = await emailResp.text();
          console.log(`  FAIL ${tenant.domain}: ${err.slice(0, 80)}`);
          skipped++;
        }
      } catch (e) {
        console.log(`  ERR ${tenant.domain}: ${e}`);
        skipped++;
      }

      await new Promise(r => setTimeout(r, 1000));
    }
  }

  // Split Group A into thirds for A/B/C testing
  const third = Math.ceil(GROUP_A.length / 3);
  const GROUP_A1 = GROUP_A.slice(0, third);
  const GROUP_A2 = GROUP_A.slice(third, third * 2);
  const GROUP_A3 = GROUP_A.slice(third * 2);

  if (GROUP === "a" || GROUP === "a1" || GROUP === "all") await sendToGroup(GROUP_A1, "clean", `Group A1: Clean - "I built a free AI assistant" (${GROUP_A1.length})`);
  if (GROUP === "a" || GROUP === "a2" || GROUP === "all") await sendToGroup(GROUP_A2, "gaps", `Group A2: Clean - "I tested from a customer's perspective" (${GROUP_A2.length})`);
  if (GROUP === "a" || GROUP === "a3" || GROUP === "all") await sendToGroup(GROUP_A3, "personal", `Group A3: Clean - "I'm Jakub, CS student" (${GROUP_A3.length})`);
  if (GROUP === "b" || GROUP === "all") await sendToGroup(GROUP_B, "gaps", `Group B: Gaps - tested from customer perspective (${GROUP_B.length})`);
  if (GROUP === "c" || GROUP === "all") await sendToGroup(GROUP_C, "personal", `Group C: Timeouts - personal intro (${GROUP_C.length})`);

  console.log(`\n=== DONE === Sent: ${sent} | Skipped: ${skipped}`);
}

main().catch(console.error);
